spring.application.name=soaclientes
server.port=8082

spring.datasource.url=jdbc:postgresql://ep-sweet-frog-amvfuyj3-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
# ELIMINAR estas líneas:
# spring.jackson.default-property-inclusion=non_null
# (no hay configuración específica de XML)

# AGREGAR configuración JSON:
spring.jackson.default-property-inclusion=non_null
spring.jackson.property-naming-strategy=SNAKE_CASE


# src/main/resources/application.properties
pedidos.service.url=http://localhost:8082


# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.show-actuator=true
# Forzar Swagger a usar JSON y evitar conflictos con XML
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.content-type=application/json
springdoc.writer-with-default-pretty-printer=true
